### ISSUE TITLE
Agregar el parámetro initialValue al fakeReduce 

### ISSUE THREAD

**Issue by quintanamartin** [leotocca/fakeMDN#24]
@carigonz  el fakeReduce lo habias hecho vos no? Esta tarea la podras hacer vos?

**Comment by quintanamartin** [comment]
@srmaikol  Le pifie, creo que lo hiciste vos esto. Habiamos quedado que le metias vos a esta tarea no?

**Comment by nhsz** [comment]
Por las dudas para que tengan la referencia de lo que tienen que usar, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters
