### ISSUE TITLE
Implementar el método fakeArrayMax

### ISSUE THREAD

**Issue by quintanamartin** [leotocca/fakeMDN#26]

**Comment by quintanamartin** [comment]
@srmaikol Estuve releyendo algunas cosas del codigo y vi que por momentos pasamos del ingles al español. Por ejemplo hay una variable que se llama comienzo. Podras modificarlo?
Gratzie!

**Comment by quintanamartin** [comment]
Otra cosa! No deberiamos usar VAR. Se me paso :(

**Comment by srmaikol** [comment]
ya cambié el nombre de la variable comienzo a begin
uso de var: fijate que la variable en cuestión la necesito usar dentro de un lazo for, por eso debo usar var, ya que const y let no tienen scope dentro del bloque for

**Comment by nhsz** [comment]
@quintanamartin @srmaikol [acá](https://github.com/leotocca/fakeMDN/issues/33#issuecomment-503340014) les dejé un ejemplo de cómo deberían mover la variable a un scope superior para poder usarla tranquilamente, si es lo que necesitan. 

No hay necesidad de usar `var`. De todas formas también plantié ahí que lo que deberían buscar es una solución alternativa al problema, más simple, que no necesite esa variable extra.
