### ISSUE TITLE
Cosas a arreglar para el sprint 3

### ISSUE THREAD

**Issue by nhsz** [leotocca/fakeMDN#33]
- Hacer las comparaciones usando la [igualdad estricta](https://github.com/leotocca/fakeMDN/blob/547fae4765a399a8e410ec984f431d78a6d3b181/app.js#L2) (esto se menciona en las [buenas prácticas](https://github.com/undefinedschool/best-practices#javascript))
- Qué devuelve [`fakeFind`](https://github.com/leotocca/fakeMDN/blob/547fae4765a399a8e410ec984f431d78a6d3b181/app.js#L63) si el elemento no está en el array? La respuesta está en MDN...
- Definieron [`fakeIncludes`](https://github.com/leotocca/fakeMDN/blob/547fae4765a399a8e410ec984f431d78a6d3b181/app.js#L104) 2 veces, sólo tiene que estar la versión que usa ´fakeIndexOf´
- Usar [desigualdad estricta](https://github.com/leotocca/fakeMDN/blob/547fae4765a399a8e410ec984f431d78a6d3b181/app.js#L105) para hacer la comparación
- Ok, acá hay espanglish y un var. No usamos var, [por favor arreglar esto](https://github.com/leotocca/fakeMDN/blob/547fae4765a399a8e410ec984f431d78a6d3b181/app.js#L14)
- Falta el parámetro `initialValue` en el [`fakeReduce`](https://github.com/leotocca/fakeMDN/blob/547fae4765a399a8e410ec984f431d78a6d3b181/app.js#L11)
- No entiendo el uso de la variable `comienzo` en el [`fakeReduce`](https://github.com/leotocca/fakeMDN/blob/547fae4765a399a8e410ec984f431d78a6d3b181/app.js#L11), es necesaria?
- No mandar cosas a master si no pasan por un PR + Code Review. [`fakeIntersection`](https://github.com/leotocca/fakeMDN/blob/547fae4765a399a8e410ec984f431d78a6d3b181/app.js#L108) fue probado? No funciona, chequear los nombres de las variables
- Poner el [`script` tag de `app.js`](https://github.com/leotocca/fakeMDN/blob/547fae4765a399a8e410ec984f431d78a6d3b181/index.html#L6) al final del ´body´ para no bloquear la carga de la página
La clase [´titulohome´](https://github.com/leotocca/fakeMDN/blob/547fae4765a399a8e410ec984f431d78a6d3b181/index.html#L19) no existe en el CSS, sacarla si no se usa
- Los nombres de las clases de CSS deben ser descriptivos. Si hay una clase que se llama `container`, `container1` y `container2` no son buenos nombres

**Comment by srmaikol** [comment]
Respecto a `fakeReduce`:

- Para poder reutilizar `fakeReduce `en funciones como `fakeMin `y `fakeMax`, no servía el `initialValue `por default en `fakeReduce `( por ejemplo, si ponia por default 0, no funcionaba con strings), le da una utilidad limitada.
Por este motivo implementé  `fakeReduce` para q funcione igual q el `array.reduce` original: si no hay `initialValue`, toma por defecto como `initialValue `el primer elemento del array y arranca a procesar en el segundo. Espero que sea aceptado, aunque no era la consigna, entiendo q es una versión mejorada!

- La variable `comienzo` (ya la renombré `begin`) es justamente para eso, indica donde debe empezar a procesar el `fakeReduce`, en la posición 0 o en la 1 del array

- Uso de `var`: necesitaba usar la variable comienzo dentro del `for`, eso no me lo permiten ni `let `ni `const`, entiendo q ahí el `var `está justificado o hay otra manera?

**Comment by nhsz** [comment]
- La consigna no pedía utilizar reduce para implementar `fakeArrayMin` y `fakeArrayMax`, pero es bienvenido si lo hacen
- No es necesario usar `var`
- El `initialValue` no tiene por qué ser 0, cómo explica [acá](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#Parameters), si no recibe valor, `initialValue` es el 1er elemento del array. Usando eso funciona en `fakeMin` y `fakeMax`

**Comment by srmaikol** [comment]
ok!
Respecto al uso de `var`:
Yo defino la variable `begin `dentro de un `if`. Con `var `funciona, con `let `o `const ` no funciona, como en este ejemplo:
```
if (true) {
  var begin=10;
}
console.log(begin);
}

```

**Comment by quintanamartin** [comment]
@nhsz el FakeFind tiene como valor de retorno:
Primer elemento del array que cumpla la condicion o undefined
En MDN dice:
El valor del primer elemento del array que cumple la función de prueba proporcionada; de lo contrario, devuelve undefined.

Estaria mal planteado lo que puse?

**Comment by nhsz** [comment]
> @nhsz el FakeFind tiene como valor de retorno:
> Primer elemento del array que cumpla la condicion o undefined
> En MDN dice:
> El valor del primer elemento del array que cumple la función de prueba proporcionada; de lo contrario, devuelve undefined.
> 
> Estaria mal planteado lo que puse?

Si, que le falta el return `undefined`

**Comment by nhsz** [comment]
> ok!
> Respecto al uso de `var`:
> Yo defino la variable `begin `dentro de un `if`. Con `var `funciona, con `let `o `const ` no funciona, como en este ejemplo:
> 
> ```
> if (true) {
>   var begin=10;
> }
> console.log(begin);
> }
> ```

`let`/`const` tienen scope por bloque, si necesitás usar esa variable la subís arriba.

```
function fakeReduce(arr, callbackFunction, accumulator) {
  let comienzo = 0;

  if (accumulator == undefined) { // esto no puede pasar
    accumulator = arr[0];
    comienzo = 1;
  }

  for (let i = comienzo; i < arr.length; i++) {
    accumulator = callbackFunction(accumulator, arr[i]);
  }
  return accumulator;
}
```

Otra cosa, el acumulador nunca puede tomar el valor `undefined`.

Pero de nuevo, no es necesaria. Fíjensen bien lo que hace el `reduce`.

**Comment by srmaikol** [comment]
ok! lo que yo llamo accumulator es en realidad initialValue que después lo uso de acumulador, me quise ahorrar un nombre de variable pero generé confusión

**Comment by nhsz** [comment]
Pero son 2 cosas distintas, `initialValue` es otro parámetro, que tiene que estar.
