### ISSUE TITLE
Reescribir las funciones como métodos de Array, usando el prototype

### ISSUE THREAD

**Issue by leotocca** [leotocca/fakeMDN#48]

**Comment by leotocca** [comment]
Adaptar la documentación (sintaxis, ejemplos, etc) donde corresponda

**Comment by carigonz** [comment]
@leotocca @srmaikol @quintanamartin 
Quise trabajar en esto pero no entendi porque hay metodos estan escritos con `const` y seguidos de una `arrow function` en vez del Array.prototype. 
Alguien me explica si esto es un error porque yo entendi que todas las funciones deben ser extendidas del array prototype :confused:

Deje otro comentario en el PR

**Comment by srmaikol** [comment]
listo
