### ISSUE TITLE
Cosas a fixear para la segunda entrega

### ISSUE THREAD

**Issue by nhsz** [leotocca/fakeMDN#9]
- [x] 1. falta linkear el `fakeForEach.html` en el `index.html`
- [x]  2. En el `fakeForEach.html`, completar la sección de parámetros
- [x]  3. [`forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) ejecuta el _callback_ pasado por parámetro por cada elemento del array, pero [no debe modificar](https://github.com/leotocca/fakeMDN/blob/40d185c9381b920a58987c7995ea1fe44a9a4226/app.js#L27) el array
- [x] 4. usar `<code>`, tag semántico, para secciones de código. Investigar https://highlightjs.org/ para resaltado de sintaxis
- [x] 5. Usar `for... of` en lugar del for común si no nos interesa el índice
- [x] 6. El título de cada página de info de un método debe ser el nombre del método , ej, en el `fakeForEach.html`, el título debe ser `fakeForEach`
- [x] 7. Borrar los comentarios del código que sean redundantes. Usar [comentarios minimales](https://github.com/undefinedschool/best-practices/blob/master/README.md#comentarios)
- [x] 8. Borrar las cosas comentadas que no se utilicen
- [x] 9. Usar nombres declarativos para las variables. Si la variable va a guardar una [lista de valores filtrados](https://github.com/leotocca/fakeMDN/blob/40d185c9381b920a58987c7995ea1fe44a9a4226/app.js#L13). `filteredList` por ejemplo, es un mejor nombre que `newArr`, que es genérico
- [x] 10. Utilizar _tags semánticos_ en lugar de _divs genéricos_
- [x] 11. Si van a nombrar variables y funciones en inglés, las clases de css tmb tienen que estar en inglés
- [x] 12. En lo posible aplicar estilos siempre utilizando clases
- [x] 13. Mover los htmls de cada función a una carpeta aparte, por ejemplo `methodsInfo` (esto va a requerir actualizar los links relativos), dejando sólo el `index.html` suelto
- [x] 14. Usar [`const` por default](https://github.com/undefinedschool/best-practices#javascript) al declarar variables, salvo que sepamos que las vamos a _reasignar_. Recordar que un arreglo puede modificarse aún si es declarado usando `const`.
- [x] 15. [`forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) no retorna nada, por lo tanto, [`fakeForEach`](https://github.com/leotocca/fakeMDN/blob/40d185c9381b920a58987c7995ea1fe44a9a4226/app.js#L24) tampoco debe hacerlo
- [x] 16. Cuando vamos a devolver un `booleano`, muchas veces alcanza con devolver el resultado de la expresión. Ejemplo:

```js
/*  
 ** Caso 1 ❌ 
 ** Es redundante, `a > b` ya es una _expresión booleana_, 
 ** por lo tanto evalúa a `true` ó `false`
 */ 

if (a > b) {
  return true;
} else {
  return false;
}

/*  
 ** Caso 2 ✅
 ** Retornamos directamente el resultado de la expresión
 */ 

return a > b;
```

**Comment by quintanamartin** [comment]
Chicos, ya hice la parte del for...of en fakeForEach

**Comment by quintanamartin** [comment]
Chicos, tambien pude completar el html del index.

**Comment by quintanamartin** [comment]
Buenas gente! Estuve viendo el codigo, arregle varios de los puntos que pidio Nico en este issue!

**Comment by carigonz** [comment]
nico, el issue 9 te referis a las variables en app.js ??

**Comment by nhsz** [comment]
> nico, el issue 9 te referis a las variables en app.js ??

Ahí puse una referencia a la línea, dice `newArr`, la idea es cambiarlo por algo más declarativo

**Comment by nhsz** [comment]
Hola hola probando menciones @leotocca @srmaikol @carigonz @quintanamartin cambio

**Comment by carigonz** [comment]
@nhsz completado el punto 9)

**Comment by nhsz** [comment]
Pueden cerrar el issue entonces 👍
